name: idq-tiger-app
version: 1.0.0

runtime:
  type: python
  version: "3.10"

entry_point: backend/main.py

frontend:
  path: frontend
  build: npm run build
  output: ../backend/static

command: [
  "gunicorn",
  "backend.main:app",
  "-w", "2",
  "-b", "0.0.0.0:8000"
]
env:
- name: NEXT_PUBLIC_DEPLOYMENT_MODE
  value: "integrated"
